function handle_request(env)
        uhttpd.send("Status: 200 OK\r\n")
		uhttpd.send("Access-Control-Allow-Origin: *\r\n")
		uhttpd.send("Access-Control-Allow-Headers: content-type\r\n")
		uhttpd.send("Access-Control-Allow-Methods: POST, OPTIONS\r\n")
		uhttpd.send("Access-Control-Allow-Credentials: true\r\n")
        uhttpd.send("Content-Type: text/html\r\n\r\n")
	uhttpd.send("<html><title>Info</title><body>")
        uhttpd.send("<p>---------------------------</p>")
        uhttpd.send("NOT SUPPORT CONFIG VIA WIFI</p>")
        uhttpd.send("HAVE A NICE DAY</p>")
        uhttpd.send("<p>---------------------------</p><p>")
	uhttpd.send("</p><p>")
        uhttpd.send(os.execute("uptime"))
        uhttpd.send("</p><p>WAN IP -> [")
	uhttpd.send(os.execute(". /lib/functions/network.sh; network_get_ipaddr ip wan; echo $ip;echo ']';"));
	uhttpd.send("</p><p>MAC ADDRESS -> [")
	uhttpd.send(os.execute("./root/get_macaddr.sh; echo ']';"))
	uhttpd.send("</p><p></p>---------------------------</p>")
        uhttpd.send("<p><a href='/home'>Refresh</a></p>")
        uhttpd.send("</body></html>")
end
